apiVersion: v1
kind: ConfigMap
metadata:
  name: hdfs-config
data:
  REPLICATION_FACTOR: "2"
  NAMENODE_HOST: "hdfs-namenode"
  NAMENODE_PORT: "5000"
  NAMENODE_HEARTBEAT_PORT: "6000"
  DATANODES: "hdfs-datanode-0=hdfs-datanode-0.hdfs-datanode:5001,hdfs-datanode-1=hdfs-datanode-1.hdfs-datanode:5001,hdfs-datanode-2=hdfs-datanode-2.hdfs-datanode:5001"